# Generated by Django 3.2.13 on 2022-11-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Is_owner',
            field=models.BooleanField(default=False),
        ),
    ]
