# Generated by Django 3.2.13 on 2022-11-06 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
