# Generated by Django 3.2.13 on 2022-11-02 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20221102_2146'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='foodtag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.foodtag'),
        ),
        migrations.AlterField(
            model_name='review',
            name='thematag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.thematag'),
        ),
    ]
