# Generated by Django 3.2.13 on 2022-11-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221102_2147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='foodtag_id',
        ),
        migrations.RemoveField(
            model_name='review',
            name='thematag_id',
        ),
    ]
