# Generated by Django 3.2.13 on 2022-11-03 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20221102_2149'),
        ('reviews', '0005_alter_review_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.store'),
        ),
    ]
