# Generated by Django 3.2.13 on 2022-11-01 09:24

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_name', models.CharField(max_length=100)),
                ('store_address', models.CharField(max_length=100)),
                ('store_grade', models.IntegerField()),
                ('store_tel', models.IntegerField()),
                ('store_liked', models.IntegerField(default=0)),
                ('store_image', models.ImageField(upload_to='stores')),
                ('store_x', models.IntegerField(default=0)),
                ('store_y', models.IntegerField(default=0)),
                ('image', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='stores/')),
            ],
        ),
    ]
