# Generated by Django 3.2.13 on 2022-11-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_grade',
            field=models.IntegerField(default=0),
        ),
    ]
