# Generated by Django 3.2.13 on 2022-11-03 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_x',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_y',
            field=models.CharField(default=0, max_length=100),
        ),
    ]
