# Generated by Django 3.2.13 on 2022-11-03 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='kakako_id',
            new_name='kakao_id',
        ),
    ]
