# Generated by Django 3.2.13 on 2022-11-03 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_rename_kakako_id_store_kakao_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_tel',
            field=models.CharField(max_length=100),
        ),
    ]
