# Generated by Django 3.2.13 on 2022-11-02 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_alter_store_store_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='foodtag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.foodtag'),
        ),
        migrations.AlterField(
            model_name='store',
            name='thematag_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='stores.thematag'),
        ),
    ]
