# Generated by Django 3.2.13 on 2022-11-03 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_auto_20221103_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_tel',
            field=models.IntegerField(default=0),
        ),
    ]
