# Generated by Django 3.2.13 on 2022-11-02 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_auto_20221102_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='foodtag_id',
        ),
        migrations.RemoveField(
            model_name='store',
            name='thematag_id',
        ),
    ]
